[window]
# decorations = "buttonless"
decorations = "full"
option_as_alt = "Both"
opacity = 0.9
# startup_mode = "Maximized"

[font]
size = 19

[font.normal]
# family = "Menlo Nerd Font"
# family = "Iosevka Nerd Font"
family = "PlemolJP Console NF"
style = "Regular"

# moving between tmux windows cmd+a, cmd+s, cmd+d etc..
[[keyboard.bindings]]
key = "A"
mods = "Alt"
chars = "\u001ba"

[[keyboard.bindings]]
key = "S"
mods = "Alt"
chars = "\u001bs"

[[keyboard.bindings]]
key = "D"
mods = "Alt"
chars = "\u001bd"

[[keyboard.bindings]]
key = "F"
mods = "Alt"
chars = "\u001bf"

[[keyboard.bindings]]
key = "G"
mods = "Alt"
chars = "\u001bg"

[[keyboard.bindings]]
key = "Z"
mods = "Alt"
chars = "\u001bz"

[[keyboard.bindings]]
key = "X"
mods = "Alt"
chars = "\u001bx"

[[keyboard.bindings]]
key = "C"
mods = "Alt"
chars = "\u001bc"

[[keyboard.bindings]]
key = "V"
mods = "Alt"
chars = "\u001bv"

[selection]
save_to_clipboard = true

[[keyboard.bindings]]
key = "C"
mods = "Command"
action = "Copy"

[[keyboard.bindings]]
key = "V"
mods = "Command"
action = "Paste"

# moving through vim buffers(bufferline)
[[keyboard.bindings]]
key = "1"
mods = "Command"
chars = "\u001b1"

[[keyboard.bindings]]
key = "2"
mods = "Command"
chars = "\u001b2"

[[keyboard.bindings]]
key = "3"
mods = "Command"
chars = "\u001b3"

[[keyboard.bindings]]
key = "4"
mods = "Command"
chars = "\u001b4"

[[keyboard.bindings]]
key = "5"
mods = "Command"
chars = "\u001b5"

[[keyboard.bindings]]
key = "6"
mods = "Command"
chars = "\u001b6"

[[keyboard.bindings]]
key = "7"
mods = "Command"
chars = "\u001b7"

[[keyboard.bindings]]
key = "8"
mods = "Command"
chars = "\u001b8"

[[keyboard.bindings]]
key = "9"
mods = "Command"
chars = "\u001b9"

[[keyboard.bindings]]
key = "0"
mods = "Command"
chars = "\u001b0"

[colors.primary]
background = '#000000'

[cursor]
style = "Underline"

[env]
TERM = "xterm-256color"
