[window]
# decorations = "buttonless"
decorations = "full"
option_as_alt = "Both"
opacity = 0.9
# startup_mode = "Maximized"

[font]
size = 19

[font.normal]
# family = "Menlo Nerd Font"
# family = "Iosevka Nerd Font"
family = "PlemolJP Console NF"
style = "Regular"

[colors.primary]
background = '#000000'

[cursor]
style = "Underline"

[env]
TERM = "xterm-256color"

[selection]
save_to_clipboard = true

[[keyboard.bindings]]
key = "C"
mods = "Command"
action = "Copy"

[[keyboard.bindings]]
key = "V"
mods = "Command"
action = "Paste"

# tmux doesn't work ctrl + <digit> without this
# [[keyboard.bindings]]
# key = "Key1"
# mods = "Control"
# chars = "\u001B[49;5u"
# [[keyboard.bindings]]
# key = "Key2"
# mods = "Control"
# chars = "\u001B[50;5u"
#
# [[keyboard.bindings]]
# key = "Key3"
# mods = "Control"
# chars = "\u001B[51;5u"
#
# [[keyboard.bindings]]
# key = "Key4"
# mods = "Control"
# chars = "\u001B[52;5u"
